version: '3.1'
services:
  app:
    build: .
    ports:
      - 8989:8989
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trendyoldb